data:
  mrc_data_module: MrcDataModule
  retriever_data_module: RetrieverDataModule
  dataset_name: [klue_mrc, squad_kor_v1]
  preprocessing_num_workers: 1
  max_seq_length: 384
  max_answer_length: 30
  doc_stride: 128
  batch_size: 4
  n_best_size: 5
  num_neg: 2

model:
  encoder_plm_name: klue/bert-base
  encoder: BertEncoder
  mrc_plm_name: klue/bert-base


loss: nll_loss

metric:
  mrc: [squad, bleu]
  retriever: [accuracy, f1]

optimizer:
  name: AdamW
  lr: 2e-5

train:
  output_dir: "./outputs"
  num_train_epochs: 2

device: cuda