data:
  data_module: MrcDataModule
  dataset_name: [default]
  preprocessing_num_workers: 1
  max_seq_length: 384
  max_answer_length: 30
  doc_stride: 128
  batch_size: 8
  n_best_size: 5

model:
  plm_name: sangrimlee/bert-base-multilingual-cased-korquad

metric: [squad]

optimizer:
  name: AdamW
  lr: 5e-5

train:
  output_dir: "outputs"
  num_train_epochs: 1

wandb:
  enable: true
  project: Mrc baseline

device: cuda
