run_name: 7_category
data:
  data_module: MrcDataModule
  dataset_name: [default] #default, klue_mrc, squad_kor_v1
  preprocessing_num_workers: 1
  max_seq_length: 384
  max_answer_length: 30
  doc_stride: 128
  batch_size: 16
  n_best_size: 5
  preproc_list: [original]
  add_special_token: []

model:
  plm_name: klue/roberta-large

metric: [squad, bleu] #squad, bleu

optimizer:
  name: AdamW
  lr: 1.6764783497920226e-05

train:
  output_dir: "outputs"
  num_train_epochs: 10

wandb:
  enable: true
  project: sangyeop

device: cuda
