data:
  data_module: MrcDataModule
  dataset_name: [default] #default, klue_mrc, squad_kor_v1
  preprocessing_num_workers: 1
  max_seq_length: 384
  max_answer_length: 30
  doc_stride: 128
  batch_size: 16
  n_best_size: 5
  preproc_list: [categorize_question]
  add_special_token: [<OBJECT>, <HUMAN> , <LOCATION>, <TIME>, <ORGANIZATION>, <METHOD>, <EVENT>, ≤NUMERIC>, <RELATION>, <ETC>]

model:
  plm_name: klue/bert-base

metric: [squad, bleu] #squad, bleu

optimizer:
  name: AdamW
  lr: 0.000015

train:
  output_dir: "outputs"
  num_train_epochs: 10

wandb:
  enable: true
  project: sangyeop

device: cuda
