data:
  data_module: MrcDataModule
  dataset_name: [default] #default, klue_mrc, squad_kor_v1
  preprocessing_num_workers: 1
  max_seq_length: 384
  max_answer_length: 30
  doc_stride: 128
  batch_size: 16
  n_best_size: 5
  preproc_list: [replace_markdown_with_doc]
  add_special_token: [<DOC>, <TEST>, <TITLE>, <TITLE_END>, <HEADER>, <LIST>]

model:
  plm_name: klue/bert-base

metric: [squad, bleu] #squad, bleu

optimizer:
  name: AdamW
  lr: 1.6764783497920226e-05

train:
  output_dir: "outputs"
  num_train_epochs: 10

wandb:
  enable: true
  project: minseon

device: cuda
