prediction:  # prediction은 nbest파일 경로를 넣어 주세요!
  validation: /outputs/sep-inf50_rerank_original_default_bz=16_lr=1.7110631470130408e-05_eval_nbest_predictions.json
  test: /outputs/sep-inf50_rerank_original_default_bz=16_lr=1.7110631470130408e-05_test_nbest_predictions.json

tokenized_example:  # null을 넣으면 프로토타입에서 example별로 생성하거나, 해당 dataset 또는 prediction의 tokenized_examples 파일을 생성할 수 있습니다
  dataset: null  # /tokenized/dataset
  prediction: null  # /tokenized/sep-inf50_original_default_bz=16_lr=1.7110631470130408e-05

# retrieval:
